[package]
name = "zowe"
version = "0.4.2"
authors = ["Zowe Project"]
edition = "2018"
license = "EPL-2.0"
repository = "https://github.com/zowe/zowe-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathsearch = "0.2.0"
rpassword = "5.0.1"
sysinfo = "0.21.1"
serde_json  = "1.0.69"
serde  = { version = "1.0.130", features = ["derive"]}
dirs = "4.0.0"
uds_windows = "1.0.1"
